# Site settings
title: Shanghai Normal University (SHNU)
course_name: 科技论文写作：信息获取与表达 
course_description: "This graduate course is a dive into applied 科技论文写作：信息获取与表达. The students will learn how to implement and train neural networks in a variety of tasks across image, sound, and text processing. As a prerequisite, the students are expected to have a basic knowledge of neural networks and be familiar with the concepts behind their structure and training (backpropagation, etc)." 
course_semester: "秋季 5B108 (2024)"
description: |
    Instructor: Mengmeng Li

message: Register to our Google <a href="https://groups.google.com/forum/#!forum/dlcourse-2024/">groups page</a> to get course notifications via email.
baseurl: "/course-2024" # the subpath of your site, e.g. /blog/ haha
url: "https://landbigdata.github.io/" # the base hostname & protocol for your site
githubdir: "landbigdata/landbigdata.github.io"

# Author/user information
email: mengmeng.li@shnu.edu.cn
twitter_username: mengbjfu 
github_username:  pilehvar
authorurl: "https://segs.shnu.edu.cn/6b/5a/c25642a813914/page.htm"
address: |
    School of Environmental and Geographical Sciences
    Shanghai Normal University
    Shanghai, China


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css', '_js']
exclude: ['develop', 'build.sh']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins:
    - jekyll-jalali
